pipeline{
    agent {label 'ec2_slavenode'}
    stages {
    

     
        stage('Setup Python Virtual ENV'){
       
      steps  {
            sh '''
            chmod +x /home/ec2-user/workspace/Django-pipeline/django/scripts/envsetup.sh 
          bash  /home/ec2-user/workspace/Django-pipeline/django/scripts/envsetup.sh 
            '''}
        }
       
        stage('Run python manage command'){
       
      steps  {
            sh '''
            chmod +x /home/ec2-user/workspace/Django-pipeline/django/scripts/python.sh 
          bash  /home/ec2-user/workspace/Django-pipeline/django/scripts/python.sh 
            '''}
        }
        stage('SonarQube analysis') {
  // requires SonarQube Scanner 2.8+
        def scannerHome = tool '/home/ec2-user/sonar';
        withSonarQubeEnv('Sonarqube 7.9.1 ') {
        sh "${scannerHome}/bin/sonar-scanner"
        }
      }
        
    }
}
